services:
  - type: web
    name: bot-telegram-php
    env: docker
    region: oregon
    buildContext: .
    dockerfilePath: Dockerfile
    ports:
      - port: 80
        targetPort: 80
    routes:
      - path: /
        target: /
