services:
  - type: web
    name: bot-telegram-php # Cambia el nombre si lo deseas
    env: php
    region: oregon # Elige la región que prefieras
    buildCommand: composer install # Si usas Composer para alguna dependencia
    startCommand: php -S 0.0.0.0:$PORT bot.php
    routes:
      - path: /
        target: /
