services:
  - type: web
    name: bot-telegram-php
    env: docker # Cambia el entorno a docker ya que ahora lo estamos usando
    region: oregon
    buildContext: . # Indica el directorio de construcción (la raíz del repositorio)
    dockerfilePath: Dockerfile # Especifica la ruta al Dockerfile
    ports:
      - port: 80
        targetPort: 80
    routes:
      - path: /
        target: /
